name: business-categories

features:
    words:
        embedding_dim: 100
        lowercase_tokens: true
    chars:
        embedding_dim: 8
        encoder:
            type: cnn
            num_filters: 50
            ngram_filter_sizes: [ 4 ]
        dropout: 0.2

encoder:
    hidden_size: 512
    num_layers: 2
    dropout: 0.5
    type: lstm

head:
    type: TextClassification
    pooler:
        type: boe
    labels: ['Allgemein채rzte', 'Apotheken', 'Architekturb체ros',
             'Autowerkst채tten', 'Dienstleistungen', 'Edv', 'Elektriker',
             'Elektrotechnik', 'Friseure', 'Gebrauchtwagen',
             'Handelsvermittler Und -vertreter', 'Hotels', 'Maler',
             'Physiotherapie', 'Restaurants', 'Sanit채rinstallationen',
             'Tiefbau', 'Unternehmensberatungen', 'Vereine', 'Vermittlungen',
             'Versicherungsvermittler', 'Werbeagenturen']