stages:
  - build
  - docker
  - test
  - deploy

build:package:
  image: python:latest

  stage: build

  cache:
    paths:
      - .cache/pip
      - venv/
      - .eggs/

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - make dev

  script:
    - make dist

  artifacts:
    paths:
      - dist/*.whl

build:docker:
  image: docker:latest

  stage: docker

  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  dependencies:
    - build:package

  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/biome:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/biome:$CI_COMMIT_REF_SLUG"

  only:
    - master
    - develop