language: python

services:
  - elasticsearch

python:
  - "3.7"

before_install:
  - echo "$RECOGNAI_PYPI_IP $RECOGNAI_PYPI_HOSTNAME" | sudo tee -a /etc/hosts
# command to install dependencies
install:
  - pip install -U pip
  - pip install -U six

script:
  - make dev dist

after_success:
  - pip install twine

deploy:
  skip_cleanup: true
  provider: script
  script: twine upload dist/*
  on:
    branch:
      - master
      - releases/*
env:
  - ES_DOC=doc
