name: biometext

channels:
- conda-forge

dependencies:
- python~=3.7.0
- pip>=20.3.0
# for building the docs
- nodejs==14.15.1
- pip:
  # testing
  - pytest>=6.2.0
  - pytest-cov>=2.10.0
  - pytest-pylint>=0.14.0
  - pytest-notebook~=0.6.0
  - wandb>=0.10.12
  - xlrd~=1.2.0
  # documentation
  - pdoc3~=0.8.1
  # development
  - pre-commit~=2.9.0
