name: biome

channels:
- pytorch
- conda-forge

dependencies:
- python~=3.6
- pip~=19.1.0
## pytorch CPU only (1.2.0 for allennlp 0.9.x
- pytorch~=1.2.0
- cpuonly
## shared dependencies
- dask~=2.0
- ujson~=1.35
- psutil~=5.6.2
## allennlp built deps
- regex
- jsonnet
- pip:
  - tensorboard~=1.6
