apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-biome-classifier
  name: biome-ui
  namespace: biome-classifier
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-biome-classifier
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: biome-classifier
        workload.user.cattle.io/workloadselector: deployment-biome-classifier
    spec:
      containers:
      - env:
        - name: BASE_URL
          value: /
        - name: ES_HOST
          value: http://elasticsearch-master.elastic.svc.cluster.local:9200
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow:5000
        - name: JUPYTER_LAB
          value: http://biome-classifier-jupyter:8888
        image: registry.gitlab.com/recognai-team/biome/web-app:classifier-ui
        imagePullPolicy: Always
        name: biome-classifier
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
