nav:
- Index: index.md
- API:
  - biome.text.about: api/biome/text/about.md
  - biome.text.api_new._impl_model: api/biome/text/api_new/_impl_model.md
  - biome.text.api_new.cli.cli: api/biome/text/api_new/cli/cli.md
  - biome.text.api_new.cli.explore: api/biome/text/api_new/cli/explore.md
  - biome.text.api_new.cli.serve: api/biome/text/api_new/cli/serve.md
  - biome.text.api_new.cli.train: api/biome/text/api_new/cli/train.md
  - biome.text.api_new.configuration: api/biome/text/api_new/configuration.md
  - biome.text.api_new.constants: api/biome/text/api_new/constants.md
  - biome.text.api_new.data.datasource: api/biome/text/api_new/data/datasource.md
  - biome.text.api_new.data.readers: api/biome/text/api_new/data/readers.md
  - biome.text.api_new.data.utils: api/biome/text/api_new/data/utils.md
  - biome.text.api_new.environment: api/biome/text/api_new/environment.md
  - biome.text.api_new.errors: api/biome/text/api_new/errors.md
  - biome.text.api_new.featurizer: api/biome/text/api_new/featurizer.md
  - biome.text.api_new.helpers: api/biome/text/api_new/helpers.md
  - biome.text.api_new.model: api/biome/text/api_new/model.md
  - biome.text.api_new.modules.encoders.time_distributed_encoder: api/biome/text/api_new/modules/encoders/time_distributed_encoder.md
  - biome.text.api_new.modules.heads.classification.defs: api/biome/text/api_new/modules/heads/classification/defs.md
  - biome.text.api_new.modules.heads.defs: api/biome/text/api_new/modules/heads/defs.md
  - biome.text.api_new.modules.heads.doc_classification: api/biome/text/api_new/modules/heads/doc_classification.md
  - biome.text.api_new.modules.heads.language_modelling: api/biome/text/api_new/modules/heads/language_modelling.md
  - biome.text.api_new.modules.heads.record_classification: api/biome/text/api_new/modules/heads/record_classification.md
  - biome.text.api_new.modules.heads.text_classification: api/biome/text/api_new/modules/heads/text_classification.md
  - biome.text.api_new.modules.heads.token_classification: api/biome/text/api_new/modules/heads/token_classification.md
  - biome.text.api_new.modules.specs.allennlp_specs: api/biome/text/api_new/modules/specs/allennlp_specs.md
  - biome.text.api_new.modules.specs.defs: api/biome/text/api_new/modules/specs/defs.md
  - biome.text.api_new.pipeline: api/biome/text/api_new/pipeline.md
  - biome.text.api_new.text_cleaning: api/biome/text/api_new/text_cleaning.md
  - biome.text.api_new.tokenizer: api/biome/text/api_new/tokenizer.md
  - biome.text.api_new.vocabulary: api/biome/text/api_new/vocabulary.md
  - biome.text.commands.explore.explore: api/biome/text/commands/explore/explore.md
  - biome.text.commands.learn.learn: api/biome/text/commands/learn/learn.md
  - biome.text.commands.serve.serve: api/biome/text/commands/serve/serve.md
  - biome.text.commands.ui.app: api/biome/text/commands/ui/app.md
  - biome.text.commands.ui.ui: api/biome/text/commands/ui/ui.md
  - biome.text.constants: api/biome/text/constants.md
  - biome.text.dataset_readers.datasource_reader: api/biome/text/dataset_readers/datasource_reader.md
  - biome.text.dataset_readers.mixins: api/biome/text/dataset_readers/mixins.md
  - biome.text.dataset_readers.sequence_classifier_dataset_reader: api/biome/text/dataset_readers/sequence_classifier_dataset_reader.md
  - biome.text.dataset_readers.sequence_pair_classifier_dataset_reader: api/biome/text/dataset_readers/sequence_pair_classifier_dataset_reader.md
  - biome.text.dataset_readers.text_transforms: api/biome/text/dataset_readers/text_transforms.md
  - biome.text.environment: api/biome/text/environment.md
  - biome.text.helpers: api/biome/text/helpers.md
  - biome.text.interpreters.integrated_gradient: api/biome/text/interpreters/integrated_gradient.md
  - biome.text.models.archival: api/biome/text/models/archival.md
  - biome.text.models.biome_bimpm: api/biome/text/models/biome_bimpm.md
  - biome.text.models.language_model: api/biome/text/models/language_model.md
  - biome.text.models.mixins: api/biome/text/models/mixins.md
  - biome.text.models.multifield_bimpm: api/biome/text/models/multifield_bimpm.md
  - biome.text.models.sequence_classifier: api/biome/text/models/sequence_classifier.md
  - biome.text.models.sequence_classifier_base: api/biome/text/models/sequence_classifier_base.md
  - biome.text.models.sequence_pair_classifier: api/biome/text/models/sequence_pair_classifier.md
  - biome.text.models.similarity_classifier: api/biome/text/models/similarity_classifier.md
  - biome.text.pipelines.biome_bimpm: api/biome/text/pipelines/biome_bimpm.md
  - biome.text.pipelines.defs: api/biome/text/pipelines/defs.md
  - biome.text.pipelines.explore: api/biome/text/pipelines/explore.md
  - biome.text.pipelines.learn.allennlp.callbacks.evaluate: api/biome/text/pipelines/learn/allennlp/callbacks/evaluate.md
  - biome.text.pipelines.learn.allennlp.callbacks.logging: api/biome/text/pipelines/learn/allennlp/callbacks/logging.md
  - biome.text.pipelines.learn.allennlp.default_callback_trainer: api/biome/text/pipelines/learn/allennlp/default_callback_trainer.md
  - biome.text.pipelines.learn.allennlp.defs: api/biome/text/pipelines/learn/allennlp/defs.md
  - biome.text.pipelines.learn.allennlp.learn: api/biome/text/pipelines/learn/allennlp/learn.md
  - biome.text.pipelines.multifield_bimpm: api/biome/text/pipelines/multifield_bimpm.md
  - biome.text.pipelines.pipeline: api/biome/text/pipelines/pipeline.md
  - biome.text.pipelines.sequence_classifier: api/biome/text/pipelines/sequence_classifier.md
  - biome.text.pipelines.sequence_pair_classifier: api/biome/text/pipelines/sequence_pair_classifier.md
  - biome.text.pipelines.similarity_classifier: api/biome/text/pipelines/similarity_classifier.md
  - biome.text.predictors.default_predictor: api/biome/text/predictors/default_predictor.md
  - biome.text.predictors.utils: api/biome/text/predictors/utils.md
site_name: My Docs
