name: tests

on: 
  push:
    branches:
      - master
  pull_request:


jobs:
  tests_&_doc:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.8.6
          # The target architecture (x86, x64) of the Python interpreter.
          #architecture: # optional
      - name: Setup ElasticSearch
        # You may pin to the exact commit or the version.
        uses: getong/elasticsearch-action@v1.2
        with:
          # Version of elasticsearch to use
          elasticsearch version: 7.4.2
          # The port of host
          host port: 9200 # optional, default is 9200
          # The port of container
          container port: 9200 # optional, default is 9200
          # The port of host elasticsearch node port
          host node port: 9300 # optional, default is 9300
          # The port of elasticsearch node port
          node port: 9300 # optional, default is 9300
          # the discovery.type envionment
          discovery type: single-node # optional, default is single-node
      - name: install
        run: make dev

      - name: Changing from tests to documentation build
        run: echo Changing from tests to documentation build

      - name: Checkout 🛎️
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        if: ${{ github.event_name == 'push' }}
        run: cd docs &&  npm install && npm run build:site

      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      