name: tests

on: push

jobs:
  tests:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: before_install
        run: bash ./src/ci/before_install.sh
      - name: install
        run: pip install -U pip & make dev
      - name: pytest
        run: pytest
